// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40uyKA6DndX8fR7R7YCN36WxzuGQHNLc',
    appId: '1:931896274434:web:295f3d36f3e0585839011b',
    messagingSenderId: '931896274434',
    projectId: 'canbe-a',
    authDomain: 'canbe-a.firebaseapp.com',
    storageBucket: 'canbe-a.appspot.com',
    measurementId: 'G-T0KXRB96CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBhHxAdTH2EnsDGSbUX8k56W-g81xH0AM',
    appId: '1:931896274434:android:37e83755ff679c9039011b',
    messagingSenderId: '931896274434',
    projectId: 'canbe-a',
    storageBucket: 'canbe-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7E26GIYWnBuiZ7ndfAYYOL0lSo15lOeU',
    appId: '1:931896274434:ios:d37da605b7ce0dc439011b',
    messagingSenderId: '931896274434',
    projectId: 'canbe-a',
    storageBucket: 'canbe-a.appspot.com',
    iosBundleId: 'com.example.canbeaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7E26GIYWnBuiZ7ndfAYYOL0lSo15lOeU',
    appId: '1:931896274434:ios:d37da605b7ce0dc439011b',
    messagingSenderId: '931896274434',
    projectId: 'canbe-a',
    storageBucket: 'canbe-a.appspot.com',
    iosBundleId: 'com.example.canbeaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB40uyKA6DndX8fR7R7YCN36WxzuGQHNLc',
    appId: '1:931896274434:web:295f3d36f3e0585839011b',
    messagingSenderId: '931896274434',
    projectId: 'canbe-a',
    authDomain: 'canbe-a.firebaseapp.com',
    storageBucket: 'canbe-a.appspot.com',
    measurementId: 'G-T0KXRB96CE',
  );

}